"""
Week 12 - Backtest Metrics Calculator
======================================

Calculates deterministic performance metrics for historical backtests, ensuring robust
handling of edge cases (zero trades, zero winning trades, all open trades, etc.)
without division-by-zero crashes or misleading outputs.

Author: Logic Engineer
"""

from typing import Any, Dict, List
from backend.logic.backtest_specification import TradeState


def calculate_backtest_metrics(trades: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Computes deterministic performance metrics for a list of simulated trade records.

    Parameters
    ----------
    trades : list of dict
        List of trade records generated by trade_simulator.

    Returns
    -------
    dict
        Structured summary of performance metrics.
    """
    if not trades or not isinstance(trades, list):
        return {
            "total_trades": 0,
            "closed_trades": 0,
            "open_trades": 0,
            "invalid_trades": 0,
            "incomplete_trades": 0,
            "winning_trades": 0,
            "losing_trades": 0,
            "win_rate": 0.0,
            "total_pl": 0.0,
            "total_return_pct": 0.0,
            "avg_trade_return_pct": 0.0,
            "avg_winning_trade_pct": 0.0,
            "avg_losing_trade_pct": 0.0,
            "profit_factor": 0.0,
            "max_drawdown_pct": 0.0,
        }

    total_trades = len(trades)
    closed_trades_list = [t for t in trades if t.get("status") == TradeState.CLOSED]
    open_trades_list = [t for t in trades if t.get("status") == TradeState.OPEN]
    invalid_trades_list = [t for t in trades if t.get("status") == TradeState.INVALID]
    incomplete_trades_list = [t for t in trades if t.get("status") == TradeState.INCOMPLETE]

    closed_count = len(closed_trades_list)
    open_count = len(open_trades_list)
    invalid_count = len(invalid_trades_list)
    incomplete_count = len(incomplete_trades_list)

    # Winning vs Losing trades (among CLOSED trades)
    winning_trades = [t for t in closed_trades_list if t.get("pl") is not None and t.get("pl") > 0]
    losing_trades = [t for t in closed_trades_list if t.get("pl") is not None and t.get("pl") <= 0]

    win_count = len(winning_trades)
    loss_count = len(losing_trades)

    # Win Rate calculation
    win_rate = round((win_count / closed_count) * 100.0, 4) if closed_count > 0 else 0.0

    # P/L & Return calculations
    all_pls = [t.get("pl") for t in closed_trades_list if t.get("pl") is not None]
    total_pl = round(sum(all_pls), 4) if all_pls else 0.0

    all_returns = [t.get("return_pct") for t in closed_trades_list if t.get("return_pct") is not None]
    total_return_pct = round(sum(all_returns), 4) if all_returns else 0.0
    avg_trade_return_pct = round(total_return_pct / closed_count, 4) if closed_count > 0 else 0.0

    win_returns = [t.get("return_pct") for t in winning_trades if t.get("return_pct") is not None]
    avg_winning_trade_pct = round(sum(win_returns) / win_count, 4) if win_count > 0 else 0.0

    loss_returns = [t.get("return_pct") for t in losing_trades if t.get("return_pct") is not None]
    avg_losing_trade_pct = round(sum(loss_returns) / loss_count, 4) if loss_count > 0 else 0.0

    # Profit Factor calculation
    gross_profits = sum([t.get("pl") for t in winning_trades if t.get("pl") is not None])
    gross_losses = abs(sum([t.get("pl") for t in losing_trades if t.get("pl") is not None]))

    if gross_losses > 0:
        profit_factor = round(gross_profits / gross_losses, 4)
    elif gross_profits > 0:
        profit_factor = round(gross_profits, 4)
    else:
        profit_factor = 0.0

    # Maximum Drawdown calculation (Cumulative Return Series)
    max_drawdown_pct = 0.0
    if all_returns:
        cum_returns = []
        cum = 0.0
        for r in all_returns:
            cum += r
            cum_returns.append(cum)

        peak = cum_returns[0]
        max_dd = 0.0
        for val in cum_returns:
            if val > peak:
                peak = val
            dd = peak - val
            if dd > max_dd:
                max_dd = dd
        max_drawdown_pct = round(max_dd, 4)

    return {
        "total_trades": total_trades,
        "closed_trades": closed_count,
        "open_trades": open_count,
        "invalid_trades": invalid_count,
        "incomplete_trades": incomplete_count,
        "winning_trades": win_count,
        "losing_trades": loss_count,
        "win_rate": win_rate,
        "total_pl": total_pl,
        "total_return_pct": total_return_pct,
        "avg_trade_return_pct": avg_trade_return_pct,
        "avg_winning_trade_pct": avg_winning_trade_pct,
        "avg_losing_trade_pct": avg_losing_trade_pct,
        "profit_factor": profit_factor,
        "max_drawdown_pct": max_drawdown_pct,
    }
