"""
Week 12 - Historical Signal Evaluator
=====================================

Evaluates historical signals for given stock symbols and evaluation dates,
ensuring strict point-in-time temporal isolation without look-ahead bias.

Author: Logic Engineer
"""

import logging
from typing import Any, Dict, List, Optional

from backend.logic.signal_integration import run_signal_pipeline

logger = logging.getLogger(__name__)


def evaluate_historical_signal(
    symbol: str,
    evaluation_date: str
) -> Dict[str, Any]:
    """
    Evaluates point-in-time trading signal for a single stock on an explicit historical evaluation_date.

    Parameters
    ----------
    symbol : str
        NSE stock symbol (e.g., "TCS", "INFY").
    evaluation_date : str
        Explicit evaluation date in YYYY-MM-DD format.

    Returns
    -------
    dict
        Structured signal payload generated by run_signal_pipeline with explicit evaluation_date.
    """
    symbol_clean = symbol.strip().upper() if isinstance(symbol, str) else ""
    if not symbol_clean or not evaluation_date:
        return {
            "symbol": symbol_clean,
            "evaluation_date": evaluation_date,
            "signal_valid": False,
            "is_eligible": False,
            "recommendation": "INVALID",
            "reason": "MISSING_SYMBOL_OR_DATE",
            "missing_inputs": ["symbol" if not symbol_clean else "evaluation_date"]
        }

    try:
        signal_res = run_signal_pipeline(symbol_clean, evaluation_date=evaluation_date)
        return signal_res
    except Exception as exc:
        logger.error(f"Error evaluating historical signal for {symbol_clean} on {evaluation_date}: {exc}")
        return {
            "symbol": symbol_clean,
            "evaluation_date": evaluation_date,
            "signal_valid": False,
            "is_eligible": False,
            "recommendation": None,
            "reason": f"EVALUATION_ERROR: {str(exc)}",
            "missing_inputs": []
        }


def evaluate_historical_signals(
    symbol: str,
    evaluation_dates: List[str]
) -> List[Dict[str, Any]]:
    """
    Evaluates point-in-time trading signals for a single stock across a list of historical evaluation_dates.

    Parameters
    ----------
    symbol : str
        NSE stock symbol.
    evaluation_dates : list of str
        List of historical evaluation dates in YYYY-MM-DD format.

    Returns
    -------
    list of dict
        Ordered list of evaluated signal records.
    """
    results = []
    for eval_date in sorted(evaluation_dates):
        signal = evaluate_historical_signal(symbol, eval_date)
        results.append(signal)
    return results
