"""
Signal Integration Service (Engine 8 - Pipeline)
================================================

Orchestrates the end-to-end signal flow for a single stock by bridging:
- Decision Engine (Opportunity Score / Recommendation)
- Data Engineer (Stop / Target Inputs)
- Signal Engine (Final V1 Signal Generation)

Author: Logic Engineer
"""

from typing import Any, Dict, Optional
import logging

from backend.engines.decision_engine import calculate_opportunity_score
from backend.data_pipeline.stop_target_input_service import get_stop_target_inputs
from backend.logic.signal_engine import generate_final_signal


def run_signal_pipeline(symbol: str, evaluation_date: Optional[str] = None) -> Dict[str, Any]:
    """
    Coordinates the end-to-end Signal Engine pipeline for a single stock.

    Parameters
    ----------
    symbol : str
        The stock symbol to evaluate.
    evaluation_date : str, optional
        The historical evaluation date, ensuring point-in-time safety.

    Returns
    -------
    dict
        The structured final signal generated by the Signal Engine.
    """
    symbol_clean = symbol.upper().strip() if isinstance(symbol, str) else str(symbol)

    # 1. Fetch Decision Engine Recommendation
    try:
        decision = calculate_opportunity_score(symbol_clean, evaluation_date=evaluation_date)
        recommendation = decision.get("recommendation")
    except Exception as error:
        logging.warning(f"Decision engine failed for {symbol_clean}: {error}")
        recommendation = None

    # 2. Fetch Data Engineer Stop/Target Inputs
    try:
        inputs = get_stop_target_inputs(symbol_clean, evaluation_date=evaluation_date)
        current_price = inputs.get("current_price")
        nearest_support = inputs.get("nearest_support")
        nearest_resistance = inputs.get("nearest_resistance")
        atr_14 = inputs.get("atr_14")
    except Exception as error:
        logging.warning(f"Data Engineer failed for {symbol_clean}: {error}")
        current_price = None
        nearest_support = None
        nearest_resistance = None
        atr_14 = None

    # 3. Generate Final Signal
    try:
        signal = generate_final_signal(
            current_price=current_price,
            nearest_support=nearest_support,
            nearest_resistance=nearest_resistance,
            atr_14=atr_14,
            recommendation=recommendation
        )
    except Exception as error:
        logging.error(f"Signal Engine logic crashed for {symbol_clean}: {error}")
        signal = {
            "signal_valid": False,
            "entry_lower": None,
            "entry_upper": None,
            "stop_loss": None,
            "target": None,
            "risk": None,
            "reward": None,
            "risk_reward_ratio": None,
            "reason": f"SIGNAL_ENGINE_ERROR: {str(error)}",
            "missing_inputs": []
        }

    # Append identification metadata
    signal["symbol"] = symbol_clean
    signal["evaluation_date"] = evaluation_date
    signal["recommendation"] = recommendation

    return signal
