"""
Logic Handoff Integration Test
==============================

This script tests that the Logic Engine (Decision Engine / Opportunity Score)
can successfully consume data from the constructed backtesting dataset.

It ensures:
1. The backtesting dataset can be built for multiple stocks.
2. The Logic Engine's data-access interfaces (`calculate_opportunity_score`)
   can consume evaluation dates from the dataset.
3. Opportunity calculations execute cleanly on all historical ranges.
"""

import unittest
import pandas as pd
from backend.data_pipeline.backtesting_dataset_service import build_backtesting_dataset
from backend.engines.decision_engine import calculate_opportunity_score

class TestLogicHandoff(unittest.TestCase):
    """
    Integration tests verifying the handoff between Data Engineering
    and the Logic Engine.
    """

    @classmethod
    def setUpClass(cls):
        cls.symbols = ["INFY", "TCS", "RELIANCE", "WIPRO"]
        cls.start_date = "2026-08-01"
        cls.end_date = "2026-08-14"

    def test_logic_engine_consumption(self):
        """
        Verify that the Logic Engine can consume the evaluation dates
        generated by the backtesting dataset.
        """
        for symbol in self.symbols:
            with self.subTest(symbol=symbol):
                # 1. Build the historical dataset (Data Engineering boundary)
                dataset = build_backtesting_dataset(
                    symbol, 
                    start_date=self.start_date, 
                    end_date=self.end_date
                )
                self.assertFalse(dataset.empty, f"Backtesting dataset is empty for {symbol}")

                # 2. Iterate through evaluation dates and feed them to the Logic Engine interface
                for _, row in dataset.iterrows():
                    eval_date = row["evaluation_date"]
                    
                    # Compute opportunity score at this specific point-in-time
                    result = calculate_opportunity_score(symbol, evaluation_date=eval_date)
                    
                    # 3. Assertions proving successful Logic Engine execution
                    self.assertEqual(result["symbol"], symbol)
                    self.assertIn(result["status"], {"VALID", "PARTIAL", "INSUFFICIENT"})
                    self.assertIn(result["recommendation"], {"BUY", "WATCH", "HOLD", "AVOID", "INSUFFICIENT_DATA"})
                    
                    # If status is VALID or PARTIAL, opportunity_score should be a valid float
                    if result["status"] in {"VALID", "PARTIAL"}:
                        self.assertIsNotNone(result["opportunity_score"])
                        self.assertGreaterEqual(result["opportunity_score"], 0.0)
                        self.assertLessEqual(result["opportunity_score"], 100.0)

if __name__ == "__main__":
    unittest.main()
